apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-deployment
spec:
  replicas: 1 # You can increase this depending on your needs
  selector:
    matchLabels:
      app: saleor
  template:
    metadata:
      labels:
        app: saleor
    spec:
      containers:
        - name: saleor
          image: ghcr.io/saleor/saleor:3.15.0
          ports:
            - containerPort: 3009 # Your application's port
